[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
clap.workspace = true
glob.workspace = true
libc-support-tools = { path = "../crates/libc-support-tools" }
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
toml.workspace = true
walkdir.workspace = true
